/** Canonical contract: workflows execute; presets configure workflows. */
export type VideoWorkflowId = "standard-video" | "cinematic-video" | "viral-video" | "image-to-video" | "character-video" | "lip-sync-video";
export type VideoPreset = { id: string; label: string; workflowId: VideoWorkflowId; params?: Record<string, unknown> };
export const VIDEO_WORKFLOWS: Record<VideoWorkflowId, { id: VideoWorkflowId; label: string; provider: string }> = {
  "standard-video": { id: "standard-video", label: "Standard Video", provider: "modelark" }, "cinematic-video": { id: "cinematic-video", label: "Cinematic Video", provider: "modelark" }, "viral-video": { id: "viral-video", label: "Viral Video", provider: "modelark" }, "image-to-video": { id: "image-to-video", label: "Image to Video", provider: "modelark" }, "character-video": { id: "character-video", label: "Character Video", provider: "modelark" }, "lip-sync-video": { id: "lip-sync-video", label: "Lip Sync Video", provider: "modelark" },
};
const PRESET_WORKFLOWS: Record<string, VideoWorkflowId> = { slow_push_in: "cinematic-video", vertigo_zoom: "cinematic-video", anamorphic_dolly: "cinematic-video", golden_hour_grade: "cinematic-video", cash_rain: "viral-video", fire_meme: "viral-video", water_rap: "viral-video", neon_drip: "viral-video", character_sheet: "character-video", glitch_clone_echo: "character-video", bullet_time_photo: "image-to-video", parallax_depth: "image-to-video", album_cover_freeze: "image-to-video" };
export function resolveWorkflowForPreset(preset?: string | null, mode?: "cinematic" | "viral" | "standard"): VideoWorkflowId { const mapped = preset ? PRESET_WORKFLOWS[preset.toLowerCase().trim()] : undefined; return mapped ?? (mode === "cinematic" ? "cinematic-video" : mode === "viral" ? "viral-video" : "standard-video"); }
export function buildVideoExecutionContract(input: { preset?: string | null; mode?: "cinematic" | "viral" | "standard" }) { const workflowId = resolveWorkflowForPreset(input.preset, input.mode); return { workflow: VIDEO_WORKFLOWS[workflowId], workflowId, presetId: input.preset ?? null }; }
